title: "Anh's Space"
theme: minima
description: "Machine Learning & Information Processing"
owner: "HaiAnh-X" 

minima:
  skin: auto          
  date_format: "%b %-d, %Y"
  show_excerpts: true    
  nav_pages:
    - about.md
    - book.md


