title: "Anh's Space"
theme: minima
description: "Machine Learning and Automation"
owner: "HaiAnh-X" 

minima:
  skin: auto          
  date_format: "%b %-d, %Y"
  show_excerpts: true    
  nav_pages:
    - about.md
    - project.md
    - book.md

kramdown:
  math_engine: mathjax

